# Generated by Django 3.2.4 on 2021-06-06 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0005_auto_20210226_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='端口名')),
                ('desc', models.CharField(max_length=128, verbose_name='端口描述')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.device', verbose_name='设备')),
            ],
        ),
    ]
