# Generated by Django 3.2.4 on 2021-06-06 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0006_interface'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='interface',
            unique_together={('name', 'device')},
        ),
    ]
