---
netdevops01:
  hostname: 192.168.137.201
  username: netdevops
  password: admin123!
  port: 22
  platform: cisco_ios
  connection_options:
    napalm:
      extras:
        optional_args:
          secret: admin1234!
    netmiko:
      extras:
         conn_timeout: 60
         timeout: 180
         device_type: cisco_ios
         secret: admin1234!
  groups:
    - bj_leaf
    - netdevops
    - ios
  data:
    role: spine
    tags:
      - test
      - netdevops
      - ios
    cmds:
      - show version
 


netdevops02:
  hostname: 192.168.137.202
  username: netdevops
  password: admin123!
  port: 22
  platform: ios
  connection_options:
    napalm:
      extras:
        optional_args:
          secret: admin1234!
    netmiko:
      extras:
         conn_timeout: 60
         timeout: 180
         device_type: cisco_ios
         secret: admin1234!
  groups:
    - bj_leaf
  data:
    role: leaf
    tags:
      - test
      - netdevops
      - ios
    cmds:
      - show version
